### ISSUE TITLE
setup-cfg-fmt wipes valid empty extras

### ISSUE THREAD

**Issue by henryiii** [asottile/setup-cfg-fmt#117]
The following file is valid:

```ini
[metadata]
name = something
version = 1.0

[options]
packages = find:
install_requires =
    pytest>=6;extra == "test"

[options.extras_require]
test =
```

However, setup-cfg-fmt strips out the `extras_require.test` (and extras_require too due to #99, but the problem here is not an empty section, it's an empty item in a section), which breaks this usage of PEP 508 suggested as a replacement for https://github.com/asottile/setup-cfg-fmt/issues/81. Empty extras should not be stripped, they are still valid. (You also might want an empty extra for other reasons, like something that used to be an extra dependency and isn't anymore - even if the current handling of extras is sloppy and doesn't error if one is requested and doesn't exist). But this turns a working file into a broken one.

**Comment by asottile** [comment]
it doesn't break it:

```console
$ pip install pyupgrade[foo]
Collecting pyupgrade[foo]
  Using cached pyupgrade-2.31.0-py2.py3-none-any.whl (54 kB)
WARNING: pyupgrade 2.31.0 does not provide the extra 'foo'
Collecting tokenize-rt>=3.2.0
  Using cached tokenize_rt-4.2.1-py2.py3-none-any.whl (6.1 kB)
Installing collected packages: tokenize-rt, pyupgrade
Successfully installed pyupgrade-2.31.0 tokenize-rt-4.2.1
```

**Comment by henryiii** [comment]
> it doesn't break it:

This is what I meant by: "the current handling of extras is sloppy and doesn't error if one is requested and doesn't exist", though it's nice it produces a warning.

That's not the problem here. The bug is that with the empty extra, the `.egg-info/requires.txt` is correct:

```ini
[:extra == "test"]
pytest>=6

[test]
```

While if you remove the extra, you get:

```ini
[:extra == "test"]
pytest>=6
```

which, according to PEP 508, `extra` is not defined unless it's listed. So setup-cfg-fmt is turning a working `setup.cfg` into a broken one.

**Comment by asottile** [comment]
yeah interpolation is not going to happen
