### ISSUE TITLE
`variant=CommonMark` gets stripped from `long_description_content_type`

### ISSUE THREAD

**Issue by jack1142** [asottile/setup-cfg-fmt#122]
Minimal example:
- `setup.cfg`:
```ini
[metadata]
name = example_project
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8; variant=CommonMark
```
- `README.md`:
```markdown
# Header

text
```

`setup.cfg` gets rewritten to:
```ini
[metadata]
name = example_project
long_description = file: README.md
long_description_content_type = text/markdown
```

This spec can be found here:
https://packaging.python.org/en/latest/specifications/core-metadata/#description-content-type

**Comment by asottile** [comment]
setup-cfg-fmt unconditionally assigns that value based on the detected content type of the readme file: https://github.com/asottile/setup-cfg-fmt/blob/d3e358c2db3d8e480b207a098ade06ee2381e3f5/setup_cfg_fmt.py#L374-L380
