### ISSUE TITLE
Identify library never returns "or later" for license

### ISSUE THREAD

**Issue by garthwilliamson** [asottile/setup-cfg-fmt#137]
Ideally the reformat would leave `-or-later` on the end if it is "correct" otherwise. An alternative might be to add a new option to disable the license checks.

**Comment by asottile** [comment]
the `license` field is meant to be a SPDX identifier, "-or-later" is not a valid identifier

**Comment by garthwilliamson** [comment]
According to https://spdx.org/licenses/, there are many identifiers with the suffix, for example `GPL-2.0-or-later.` Because the `LICENSE` file is the same whether it's straight GPL or `GPL-2.0-or-later`, identify can't tell the difference.

**Comment by asottile** [comment]
ah right GPL cancer

surely if the licenses are byte identical then then `or-later` is redundant right?

**Comment by garthwilliamson** [comment]
I don't know - pypi doesn't seem to have very strict rules about getting these things exactly right, so it might not make any material difference. 

If it bothers us enough, which pull request would you prefer? Option to avoid licence changes altogether, or to keep or-later when it already exists and `GPL` is in the string?

**Comment by asottile** [comment]
does your license contain an "or later" clause in its contents? if not `-or-later` is probably not correct.  (though `identify` doesn't detect the or later clause as it is).

setup-cfg-fmt intentionally doesn't have options so definitely not that.

I suspect the actual fix is having identify identify the or later clause
