### ISSUE TITLE
license_file is deprecated - setup-cfg-fmt should remove this and convert to license_files

### ISSUE THREAD

**Issue by jbarlow83** [asottile/setup-cfg-fmt#139]
setuptools as of v62.3 warns that license_file is deprecated and license_files should be used instead.
setup-cfg-fmt currently requires license_file to exist.

**Comment by asottile** [comment]
general open source advice: [search the issue tracker next time](https://github.com/asottile/setup-cfg-fmt/issues?q=is%3Aissue+license_file+is%3Aclosed)
