### ISSUE TITLE
additional extras removed

### ISSUE THREAD

**Issue by lcnittl** [asottile/setup-cfg-fmt#140]
`setup-cfg-fmt` appears to remove any extras after the first one for requirements defined via URI:

```ini
install_requires =
    black@git+https://github.com/psf/black.git#egg=black[colorama,jupyter]
    black[colorama,jupyter]
```

```ini
install_requires =
    black@git+https://github.com/psf/black.git#egg=black[colorama
    black[colorama,jupyter]
```

Same happens for requirements defined in `[options.extras_require]`

Is there another way to define such extras? (or is it a bug)

Thanks for looking into it!

**Comment by asottile** [comment]
urls are intentionally not supported
