### ISSUE TITLE
fix: add option for defining long_description

### ISSUE THREAD

**Issue by JonasPammer** [asottile/setup-cfg-fmt#149]
Hello!
Thanks for this awesome project and you determination to open source.

I use Asciidoctor for documentation.

Because PyPI does not support rendering this format, I made a CI workflow to convert my README.adoc to a README.md before building the python wheels and uploading to PyPI etc (unrelevant to this ticket, just a info).

The current alphabetical-sort determination made by this hook ranks `.adoc` (with content_type of `text/plain`) as first, 
which results in PyPI showing `The author of this package has not provided a project description` as it does not support Asciidoctor.

I tried to do a workaround by renaming the markdown file to `README-.md` for it to rank first but then python/pypi does not like it:

```
...(README-.md file is not being copied)...

/tmp/build-env-cbglbinp/lib/python3.8/site-packages/setuptools/config/expand.py:142: UserWarning: File '/tmp/build-via-sdist-wi26p40b/test_application-0.3.6/README-.md' cannot be found
  warnings.warn(f"File {path!r} cannot be found")

warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md
```
I then tried to do a workaround by renaming the markdown file to `README`, but then this hook determines it as `text/plain`.
I reverted to commenting this pre-commit hook out for now.

I'd like to add an option for defining the filename for `long_description` like this:

```yaml
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.2
    hooks:
      - id: setup-cfg-fmt
        long_description: README.md
```

I'd love to make my first PR for this!

**Comment by asottile** [comment]
setup-cfg-fmt intentionally has no options

perhaps a better alternative would be to have it ignore .adoc files? though it sounds like adoc is causing you more trouble than benefit so maybe the fix is to just not use adoc

**Comment by JonasPammer** [comment]
oh yeah, that would be the cleaner solution. although i have written this suggestion too, for some reason i removedit in my hectic.

but, except for than this bug (and maybe [this](https://github.com/github/markup/issues/1095)) asciidoctor

**Comment by JonasPammer** [comment]
oh yeah, that would be the cleaner solution.

Switching off of Asciidoctor is no option for me,
I already went full-in on Asciidoctor for everything a long time ago, 
it enables so much more advanced documentation for everything by just using its syntax etc.

Thanks for taking the time and the quick answer, I'd be working on a PR for this now!
