### ISSUE TITLE
Incorrect handling of file:

### ISSUE THREAD

**Issue by EvaSDK** [asottile/setup-cfg-fmt#187]
According to [setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#specifying-values), values behind `file:` directive should be considered a list.

Currently, applying setup-cfg-fmt on a project using this results in:
```diff
-long_description = file: README.rst, CHANGELOG.rst
+long_description = file: README.rst
```

This usage is showcased in https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#configuring-setuptools-using-setup-cfg-files.

**Comment by asottile** [comment]
the convention setup-cfg-fmt uses is to only have the README as the long description

putting the changelog in there just feels like noise anyway

**Comment by EvaSDK** [comment]
I agree but I'm trying to on-board a project to pre-commit and having setup-cfg-fmt messing up with this against upstream wishes might force me to remove this hook :(

**Comment by asottile** [comment]
then don't use the hook, sounds easy enough to me

**Comment by EvaSDK** [comment]
I think there's more value in setup-cfg-fmt than just this option. Let me see with upstream if this is actually a showstopper or not.

**Comment by EvaSDK** [comment]
Also, not sure how it is implemented currently but you could expect similar complaints from other uses of `file:` as in package requirements.

**Comment by asottile** [comment]
I don't expect such complains because that is not the same
