### ISSUE TITLE
How to use this plugin with setup.cfg comments?

### ISSUE THREAD

**Issue by dstansby** [asottile/setup-cfg-fmt#195]
I'm trying to add some comments to setup.cfg, but it seems like `setup-cfg-fmt` strips these from the file, and I couldn't find any docs about this in the README. Is this intended behaviour? Is there a way I can keep comments in `setup.cfg`?

Here's an example section, where the lines beginning with `#` get stripped by `setup-cfg-fmt`:

```
[options.extras_require]
docs =
    napari[all]
    numpydoc
    pydata-sphinx-theme
    # Disabled for now, as doesn't work on readthedocs
    # qtgallery 
    sphinx
    sphinx-automodapi
    sphinx-gallery
```

**Comment by asottile** [comment]
please search the issue tracker

**Comment by dstansby** [comment]
Ah sorry - is there any chance a note about this could be added to the README, which is what I checked first?
