### ISSUE TITLE
automatically striping python 3.4

### ISSUE THREAD

**Issue by gaborbernat** [asottile/setup-cfg-fmt#24]
My expression of:

``
python_requires = >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
``
automatically is rewritten to:

``
python_requires = >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*
``

Why is that?

**Comment by asottile** [comment]
if you want to include eol versions, use [`--min-py3-version`](https://github.com/asottile/setup-cfg-fmt#set-python_requires)

**Comment by gaborbernat** [comment]
How do I do that via the config file, see https://github.com/pypa/virtualenv/pull/1495/files? py34 is there in tox.ini, in classifier, in python requires; feels excessive to stip it 🤔 

https://github.com/pypa/virtualenv/pull/1495/files

**Comment by asottile** [comment]
`args: [...]`

**Comment by asottile** [comment]
hmm it might be able to use `tox.ini` to find the minimum -- I can't quite remember the logic there, it's unfortunately complicated :S

multiple (incomplete) sources of info that all affect each other
