### ISSUE TITLE
Custom defined classifiers are stipped

### ISSUE THREAD

**Issue by 00willo** [asottile/setup-cfg-fmt#32]
Thanks, for this great tool for ensuring a consitent formatting of `setup.cfg`. I just came across it, and really like the intent of the project.

Unfortunately, I've hit a minor (hopefully in terms of fix as well) issue where any custom defined classifer that we have is stripped from the file.

One of the important uses for custom classifiers for us, is that we use them is to assist in preventing the unintentional uploading of internal package to pypi. Enabling a way to keep these custom classifiers, simple list of exclusions maybe via CLI would suffice.

**Comment by asottile** [comment]
could you provide an example? as far as I know classifiers are only [sorted](https://github.com/asottile/setup-cfg-fmt/blob/5077be2110ca5790dd7c3ee6a73900c489545337/setup_cfg_fmt.py#L381-L387) and/or [added](https://github.com/asottile/setup-cfg-fmt/blob/5077be2110ca5790dd7c3ee6a73900c489545337/setup_cfg_fmt.py#L374-L379) and not removed

**Comment by 00willo** [comment]
I just retested and so it does, awesome. Apologies, I must have either not been looking at the diff correctly and missed that it just moved.

Great, well I'll just close this off as it's not a bug.

**Comment by asottile** [comment]
cheers!
