### ISSUE TITLE
check mode

### ISSUE THREAD

**Issue by gaborbernat** [asottile/setup-cfg-fmt#38]
Add a ``--check`` flag that prints the diff and fails the invocation.

**Comment by asottile** [comment]
sorry, I do not want to maintain such options (consistent with the rest of the formatters I have).  version control your code and this is not necessary

**Comment by gaborbernat** [comment]
I have version controlled my code. But now in CI to check if this made changes or not, I need to invoke git which is not always the easiest.

**Comment by asottile** [comment]
you don't, `setup-cfg-fmt` exits nonzero when making changes
