### ISSUE TITLE
Add Implementation :: tags

### ISSUE THREAD

**Issue by asottile** [asottile/setup-cfg-fmt#45]
```
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy
```

can probably use `tox.ini` as a heuristic

**Comment by basic-ph** [comment]
I would like to give it a try!
Wish me luck! :smile:

**Comment by asottile** [comment]
sounds good!  I would take a look at how the current `tox.ini` code bits work

**Comment by basic-ph** [comment]
> sounds good! I would take a look at how the current `tox.ini` code bits work

do you mean something like https://github.com/asottile/setup-cfg-fmt/issues/1?

**Comment by asottile** [comment]
yep!

**Comment by quanghuynh10111-png** [comment]
[abc.py](https://github.com/user-attachments/files/25250701/abc.py)
