### ISSUE TITLE
Unable to install - error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by MarcoGorelli** [asottile/setup-cfg-fmt#46]
I have tried adding

```
  -   repo: https://github.com/asottile/setup-cfg-fmt
      rev: v1.11.0
      hooks:
      -   id: setup-cfg-fmt
      
```
to my pre-commit-config.yaml file, and then running `pre-commit run --all`. However, I then get a very long error message. I've attached the .cache/pre-commit/pre-commit.log file
[pre-commit.log](https://github.com/asottile/setup-cfg-fmt/files/5288666/pre-commit.log)

**Comment by asottile** [comment]
> editdistance/bycython.cpp:24:10: fatal error: Python.h: No such file or directory

this means you're missing the dev headers for python3.8 to build `editdistance`
