### ISSUE TITLE
classifiers should be version sorted

### ISSUE THREAD

**Issue by asottile** [asottile/setup-cfg-fmt#58]
notably they currently sort like this which seems bad:

```
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
```

**Comment by 1nF0rmed** [comment]
Where is the sorting currently being done?

**Comment by asottile** [comment]
appears to be here: https://github.com/asottile/setup-cfg-fmt/blob/af19bc2a229dd87817243ca2406dddde594d64a2/setup_cfg_fmt.py#L419

**Comment by 1nF0rmed** [comment]
Should it sort like this?
```
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
```

**Comment by asottile** [comment]
something like that yeah, or the `:: Only` could be after it.  the main thing is making it not sort `3.10` before `3.7` -- whatever's easiest

**Comment by 1nF0rmed** [comment]
Alright, can I be assigned this issue?

**Comment by asottile** [comment]
I don't really use the assignment feature, but sure go ahead and work on it

**Comment by 1nF0rmed** [comment]
Hey!
I've refactored the code as per the code review in the PR #59 
Le me know if you have any questions.
