### ISSUE TITLE
interpolation, & extras that reference other extras

### ISSUE THREAD

**Issue by tlambert03** [asottile/setup-cfg-fmt#81]
_(edited: sorry, issue got submitted before done)_

In order to create extras that reference other extras in setup.cfg, I have been using this hack/workaround mentioned in the setuptools issues: https://github.com/pypa/setuptools/issues/1260#issuecomment-438187625

```ini
[options.extras_require]
testing =
    pytest
dev =
    ipython
    mypy
    %(testing)s  # also include everything in the testing extras
```
It's been working fine for me for a while now.... though from what I gather, it really is a "hack" and seems to be taking advantage of interpolation which may be [disappearing eventually](https://github.com/pypa/setuptools/issues/889)?  

It fails with setup-cfg-fmt however:
```
  File "/site-packages/setup_cfg_fmt.py", line 280, in _req_base
    assert basem
AssertionError
```
`re.match(BASE_NAME_REGEX, lib)` fails in `_req_base`... since `lib` is the empty string, caused by the fact that the ConfigParser `cfg.get('options.extras_require', 'dev')` would insert an extra line there: `'\nipython\nmypy\n\npytest'`

Moreover, even if it _did_  work, `setup-cfg-fmt` would just return the literal `pytest` instead of the variable `%(testing)s`.

I see the problem is not related to this repo, so this is not so much a bug report as a question: do you have any workarounds for that use case that you use?  Or do you just avoid doing that altogether?

**Comment by asottile** [comment]
> avoid doing that altogether

this sounds like the best approach if you ask me -- doing interpolation in this file is asking for bugs

**Comment by tlambert03** [comment]
ok thanks!
